"""One-off generator: copies (verbatim) the classification / query functions of the original pipeline
(seminar2ענבל/audit_scripts/appeals_media_study.py and search_case_media.py) into
seminar_tool/court_rules.py, so the tool applies exactly the same rules without importing the
huge original modules.   Run:  python src/extract_court_rules.py
"""
from __future__ import annotations

import ast
import datetime as dt
import os
from pathlib import Path

# folder of the original collection pipeline (not part of this repository)
OLD = Path(os.environ.get("APPEALS_PIPELINE_DIR", "audit_scripts"))
OUT = Path(__file__).resolve().parent / "seminar_tool" / "court_rules.py"

SCM_FUNCS = ["compact_spaces", "dedupe_keep_order", "quote_phrase", "infer_case_party_names",
             "google_news_date_operators", "parse_rfc822_date"]
SCM_RENAMES = {"is_institutional_party_name": "_scm_is_institutional_party_name"}
AMS_CONSTS = ["HE_STATE", "HE_MURDER", "HE_APPEAL", "INSTITUTIONAL_PARTY_MARKERS"]
AMS_FUNCS = ["excerpt", "find_first_context", "is_offense_citation_context", "is_reduced_from_murder_to_homicide_context",
             "is_prior_criminal_history_context", "find_first_non_citation_context", "find_first_term_context",
             "classify_offense", "final_disposition_segment", "classify_appellant_type", "classify_outcome",
             "is_anonymous_name", "is_institutional_party_name", "primo_case_party_name"]


def segments(path: Path, names: list[str], consts: list[str] = ()) -> dict[str, str]:
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    out = {}
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in names:
            out[node.name] = ast.get_source_segment(src, node)
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 and getattr(node.targets[0], "id", None) in consts:
            out[node.targets[0].id] = ast.get_source_segment(src, node)
    missing = set(names) | set(consts) - set(out)
    assert not (set(names) | set(consts)) - set(out), missing
    return out


def main() -> None:
    scm = segments(OLD / "search_case_media.py", SCM_FUNCS + ["is_institutional_party_name"])
    ams = segments(OLD / "appeals_media_study.py", AMS_FUNCS, AMS_CONSTS)
    parts = [
        '"""Classification and query rules of the original study pipeline - COPIED VERBATIM (generated by',
        f'src/extract_court_rules.py on {dt.date.today().isoformat()}) from:',
        "  audit_scripts/search_case_media.py   (helpers, party names) of the original study pipeline",
        "  audit_scripts/appeals_media_study.py (classify_offense, classify_appellant_type,",
        "                                                     classify_outcome, is_anonymous_name, ...)",
        'Do not edit by hand; re-run the generator instead."""',
        "# ruff: noqa",
        "from __future__ import annotations",
        "",
        "import datetime as dt",
        "import email.utils",
        "import re",
        "from typing import Any, Callable, Iterable",
        "",
        "# ---- from search_case_media.py",
    ]
    for name in SCM_FUNCS:
        parts += [scm[name], ""]
    seg = scm["is_institutional_party_name"].replace("def is_institutional_party_name", "def _scm_is_institutional_party_name")
    parts += [seg, ""]
    # infer_case_party_names in search_case_media uses its own is_institutional_party_name
    parts[parts.index(scm["infer_case_party_names"])] = scm["infer_case_party_names"].replace(
        "is_institutional_party_name(", "_scm_is_institutional_party_name(")
    parts += ["", "# ---- from appeals_media_study.py"]
    for name in AMS_CONSTS:
        parts += [ams[name], ""]
    for name in AMS_FUNCS:
        parts += [ams[name], ""]
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print("written", OUT, OUT.stat().st_size)


if __name__ == "__main__":
    main()
