"""Classification and query rules of the original study pipeline - COPIED VERBATIM (generated by
src/extract_court_rules.py on 2026-09-25) from:
  audit_scripts/search_case_media.py   (helpers, party names) of the original study pipeline
  audit_scripts/appeals_media_study.py (classify_offense, classify_appellant_type,
                                                     classify_outcome, is_anonymous_name, ...)
Do not edit by hand; re-run the generator instead."""
# ruff: noqa
from __future__ import annotations

import datetime as dt
import email.utils
import re
from typing import Any, Callable, Iterable

# ---- from search_case_media.py
def compact_spaces(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()

def dedupe_keep_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        cleaned = compact_spaces(value)
        if cleaned and cleaned not in seen:
            seen.add(cleaned)
            out.append(cleaned)
    return out

def quote_phrase(value: str) -> str:
    escaped = value.strip().replace('"', r"\"")
    return f'"{escaped}"'

def infer_case_party_names(case_name: str) -> list[str]:
    cleaned = compact_spaces(re.sub(r"\([^)]*\)", "", case_name or ""))
    if not cleaned:
        return []
    parts = [
        compact_spaces(part.strip(" ,:;"))
        for part in re.split(r"\s+(?:נ\.|נ'|נ׳|נגד)\s+", cleaned)
        if compact_spaces(part.strip(" ,:;"))
    ]
    if len(parts) < 2:
        return []
    preferred = [part for part in parts if not _scm_is_institutional_party_name(part)]
    return dedupe_keep_order(preferred or parts)

def google_news_date_operators(start: dt.date, end: dt.date) -> tuple[str, str]:
    """Return after/before dates; before is exclusive, so add one day."""
    return start.isoformat(), (end + dt.timedelta(days=1)).isoformat()

def parse_rfc822_date(value: str) -> str:
    parsed = email.utils.parsedate_to_datetime(value)
    if parsed.tzinfo:
        parsed = parsed.astimezone(dt.timezone.utc)
    return parsed.date().isoformat()

def _scm_is_institutional_party_name(value: str) -> bool:
    cleaned = compact_spaces(value).casefold()
    institutional_terms = [
        "מדינת ישראל",
        "היועץ המשפטי",
        "התובע הצבאי",
        "לשכת עורכי הדין",
        "משטרת ישראל",
        "פרקליטות",
    ]
    return any(term in cleaned for term in institutional_terms)


# ---- from appeals_media_study.py
HE_STATE = "\u05de\u05d3\u05d9\u05e0\u05ea \u05d9\u05e9\u05e8\u05d0\u05dc"

HE_MURDER = "\u05e8\u05e6\u05d7"

HE_APPEAL = "\u05e2\u05e8\u05e2\u05d5\u05e8"

INSTITUTIONAL_PARTY_MARKERS = [
    "\u05de\u05d3\u05d9\u05e0\u05ea \u05d9\u05e9\u05e8\u05d0\u05dc",
    "\u05e8\u05e9\u05d5\u05ea",
    "\u05e2\u05e8\u05d5\u05e5",
    "\u05e4\u05e8\u05e7\u05dc\u05d9\u05d8\u05d5\u05ea",
    "\u05de\u05e9\u05e8\u05d3",
    "\u05e2\u05d9\u05e8\u05d9\u05d9\u05ea",
    "\u05d4\u05de\u05de\u05e9\u05dc\u05d4",
    "\u05d4\u05db\u05e0\u05e1\u05ea",
    "\u05e9\u05d9\u05e8\u05d5\u05ea \u05d1\u05ea\u05d9 \u05d4\u05e1\u05d5\u05d4\u05e8",
    "\u05e9\u05d1\"\u05e1",
    "\u05de\u05e9\u05d8\u05e8\u05ea \u05d9\u05e9\u05e8\u05d0\u05dc",
    "\u05d5\u05e2\u05d3\u05d4",
    "\u05e1\u05e0\u05d2\u05d5\u05e8\u05d9\u05d4",
    "\u05d4\u05e1\u05e0\u05d2\u05d5\u05e8\u05d9\u05d4",
    "\u05d4\u05d9\u05d5\u05e2\u05e5 \u05d4\u05de\u05e9\u05e4\u05d8\u05d9",
]

def excerpt(text: str, start: int, end: int, radius: int = 160) -> str:
    left = max(0, start - radius)
    right = min(len(text), end + radius)
    return compact_spaces(text[left:right])

def find_first_context(text: str, patterns: list[str]) -> tuple[str, str, int]:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            return excerpt(text, match.start(), match.end()), match.group(0), match.start()
    return "", "", -1

def is_offense_citation_context(context: str, match_start: int | None = None) -> bool:
    cleaned = compact_spaces(context)
    citation_docket = r"(?:\u05e2\"\u05e4|\u05e2\u05e4|\u05d3\u05e0\"\u05e4|\u05d3\u05e0\u05e4|\u05e8\u05e2\"\u05e4|\u05e8\u05e2\u05e4|\u05d1\u05e9\"\u05e4|\u05d1\u05e9\u05e4)\s*\d{1,6}[/-]\d{2,4}"
    citation_match = re.search(citation_docket, cleaned)
    explicit_precedent = [
        "\u05d0\u05d3\u05dd \u05e9\u05d4\u05d5\u05e8\u05e9\u05e2",
        "\u05d0\u05d3\u05dd \u05e9\u05d4\u05d5\u05d0\u05e9\u05dd",
        "\u05d4\u05de\u05e7\u05e8\u05d4 \u05e9\u05dc",
        "\u05d4\u05ea\u05d9\u05d9\u05e9\u05e0\u05d5\u05ea \u05e2\u05d1\u05d9\u05e8\u05d5\u05ea",
        "\u05d0\u05d9\u05df \u05dc\u05d4\u05e2\u05de\u05d9\u05d3 \u05d0\u05d3\u05dd \u05dc\u05d3\u05d9\u05df",
        "\u05e4\u05e9\u05e2 \u05e9\u05d3\u05d9\u05e0\u05d5",
        "\u05d4\u05e8\u05e9\u05e2\u05d5\u05ea\u05d9\u05d5 \u05d4\u05e7\u05d5\u05d3\u05de\u05d5\u05ea",
        "\u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05d3\u05e9\u05dd",
        "\u05d4\u05e2\u05d1\u05d9\u05e8\u05d5\u05ea \u05d4\u05e0\u05d8\u05e2\u05e0\u05d5\u05ea",
    ]
    citation_markers = [
        "\u05db\u05da \u05dc\u05de\u05e9\u05dc",
        "\u05dc\u05de\u05e9\u05dc",
        "\u05e8\u05d0\u05d5 ",
        "\u05e8\u05d0\u05d5:",
        "\u05d4\u05e9\u05d5\u05d5",
        "\u05e2\u05e0\u05d9\u05d9\u05df",
        "\u05dc\u05d4\u05dc\u05df:",
        "\u05e9\u05d0\u05e3 \u05d0\u05d5\u05ea\u05d5 \u05d4\u05d6\u05db\u05e8\u05ea\u05d9",
        "\u05d4\u05e4\u05e1\u05d9\u05e7\u05d4",
        "\u05d2\u05dc\u05d2\u05d5\u05dc\u05d5",
        "\u05d1\u05d9\u05ea \u05de\u05e9\u05e4\u05d8 \u05d6\u05d4 \u05d4\u05de\u05d9\u05e8",
    ]
    citation_positions = []
    if citation_match:
        citation_positions.append(citation_match.start())
    citation_positions.extend(pos for marker in citation_markers + explicit_precedent if (pos := cleaned.find(marker)) >= 0)
    if match_start is not None and citation_positions and min(citation_positions) > match_start:
        return False
    strong_citation_markers = [
        "\u05e4\"\u05d3",
        "\u05dc\u05d4\u05dc\u05df: \u05e2\u05e0\u05d9\u05d9\u05df",
        "\u05d1\u05d0\u05d5\u05ea\u05d4 \u05e4\u05e8\u05e9\u05d4",
    ]
    if any((pos := cleaned.find(marker)) >= 0 and (match_start is None or pos < match_start) for marker in strong_citation_markers):
        return True
    if citation_match and any(marker in cleaned for marker in citation_markers):
        return True
    if any(marker in cleaned for marker in explicit_precedent):
        return True
    current_case_actors = [
        "\u05d4\u05de\u05e2\u05e8\u05e2\u05e8",
        "\u05d4\u05de\u05e2\u05e8\u05e2\u05e8\u05ea",
        "\u05d4\u05de\u05d1\u05e7\u05e9",
        "\u05d4\u05de\u05d1\u05e7\u05e9\u05ea",
        "\u05d4\u05e0\u05d0\u05e9\u05dd",
        "\u05d4\u05e0\u05d0\u05e9\u05de\u05ea",
    ]
    precedent_markers = [
        "\u05e4\u05e8\u05e9\u05ea",
        "\u05e4\"\u05d3",
        "\u05d8\u05e8\u05dd \u05e4\u05d5\u05e8\u05e1\u05dd",
        "\u05e8\u05d0\u05d5 ",
        "\u05dc\u05de\u05e9\u05dc",
    ]
    return any(marker in cleaned for marker in precedent_markers) and not any(actor in cleaned for actor in current_case_actors)

def is_reduced_from_murder_to_homicide_context(context: str) -> bool:
    cleaned = compact_spaces(context)
    reduced_markers = [
        "\u05d4\u05d5\u05d7\u05dc\u05e4\u05d4 \u05e2\u05d1\u05d9\u05e8\u05ea \u05d4\u05e8\u05e6\u05d7 \u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05d4\u05d4\u05e8\u05d9\u05d2\u05d4",
        "\u05d4\u05d5\u05de\u05e8\u05d4 \u05e2\u05d1\u05d9\u05e8\u05ea \u05d4\u05e8\u05e6\u05d7 \u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05d4\u05d4\u05e8\u05d9\u05d2\u05d4",
        "\u05dc\u05d0 \u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05e8\u05e6\u05d7",
        "\u05d5\u05dc\u05d0 \u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05e8\u05e6\u05d7",
        "\u05d6\u05d5\u05db\u05d4 \u05de\u05d0\u05e9\u05de\u05ea \u05e8\u05e6\u05d7",
    ]
    if any(marker in cleaned for marker in reduced_markers) and (
        "\u05d4\u05e8\u05d9\u05d2\u05d4" in cleaned
        or "\u05d4\u05e8\u05d9\u05d2\u05ea" in cleaned
        or "\u05d2\u05e8\u05d9\u05de\u05ea \u05de\u05d5\u05d5\u05ea" in cleaned
    ):
        return True
    if (
        "\u05e0\u05d9\u05ea\u05df \u05d4\u05d9\u05d4 \u05dc\u05e9\u05e7\u05d5\u05dc \u05d4\u05e8\u05e9\u05e2\u05d4 \u05d1\u05e8\u05e6\u05d7" in cleaned
        and "\u05dc\u05d0 \u05dc\u05d4\u05d8\u05d9\u05dc" in cleaned
    ):
        return True
    if "\u05d9\u05db\u05d5\u05dc \u05dc\u05e0\u05d5\u05e2 \u05d1\u05d9\u05df" in cleaned and "\u05d4\u05e8\u05d9\u05d2\u05d4" in cleaned:
        return True
    if "\u05dc\u05d4\u05d9\u05de\u05e0\u05e2 \u05de\u05d4\u05e8\u05e9\u05e2\u05d4 \u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05e8\u05e6\u05d7" in cleaned:
        return True
    return bool(
        re.search(r"\u05d6\u05d5\u05db(?:\u05d4|\u05ea)[^.]{0,120}\u05e8\u05e6\u05d7[^.]{0,160}\u05d4\u05d5\u05e8\u05e9\u05e2[^.]{0,120}\u05d4\u05e8\u05d9\u05d2\u05d4", cleaned)
    )

def is_prior_criminal_history_context(context: str) -> bool:
    cleaned = compact_spaces(context)
    return any(
        marker in cleaned
        for marker in [
            "\u05d1\u05e2\u05d1\u05e8",
            "\u05d4\u05e8\u05e9\u05e2\u05d5\u05ea\u05d9\u05d5 \u05d4\u05e7\u05d5\u05d3\u05de\u05d5\u05ea",
            "\u05d4\u05e8\u05e9\u05e2\u05d5\u05ea\u05d9\u05d4 \u05d4\u05e7\u05d5\u05d3\u05de\u05d5\u05ea",
            "\u05d4\u05e9\u05ea\u05d7\u05e8\u05e8 \u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05de\u05de\u05d0\u05e1\u05e8",
        ]
    )

def find_first_non_citation_context(
    text: str,
    patterns: list[str],
    reject_context: Callable[[str], bool] | None = None,
) -> tuple[str, str, int]:
    for pattern in patterns:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            context = excerpt(text, match.start(), match.end())
            citation_context = excerpt(text, match.start(), match.end(), radius=160)
            citation_left = max(0, match.start() - 160)
            relative_match_start = match.start() - citation_left
            if not is_offense_citation_context(citation_context, relative_match_start) and not (reject_context and reject_context(context)):
                return context, match.group(0), match.start()
    return "", "", -1

def find_first_term_context(text: str, lowered: str, terms: list[str]) -> tuple[str, str, int]:
    for term in terms:
        pattern = rf"(?<![\u0590-\u05ff]){re.escape(term.casefold())}(?![\u0590-\u05ff])"
        for match in re.finditer(pattern, lowered):
            position = match.start()
            context = excerpt(text, position, match.end())
            citation_context = excerpt(text, position, match.end(), radius=160)
            citation_left = max(0, position - 160)
            relative_match_start = position - citation_left
            if not is_offense_citation_context(citation_context, relative_match_start):
                return context, term, position
    return "", "", -1

def classify_offense(text: str) -> dict[str, Any]:
    cleaned = compact_spaces(text)
    lowered = cleaned.casefold()
    murder_terms = [
        "\u05e2\u05d1\u05d9\u05e8\u05ea \u05e8\u05e6\u05d7",
        "\u05e0\u05d0\u05e9\u05dd \u05d1\u05e8\u05e6\u05d7",
        "\u05d4\u05d5\u05e8\u05e9\u05e2 \u05d1\u05e8\u05e6\u05d7",
        "\u05e1\u05e2\u05d9\u05e3 300",
        "\u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05dc\u05e8\u05e6\u05d7",
        "\u05de\u05d0\u05e1\u05e8 \u05e2\u05d5\u05dc\u05dd",
        HE_MURDER,
    ]
    homicide_other_terms = [
        "\u05d4\u05de\u05ea\u05d4",
        "\u05d4\u05de\u05ea\u05d4 \u05d1\u05e7\u05dc\u05d5\u05ea \u05d3\u05e2\u05ea",
        "\u05d4\u05e8\u05d9\u05d2\u05d4",
        "\u05d2\u05e8\u05d9\u05de\u05ea \u05de\u05d5\u05d5\u05ea",
        "\u05de\u05d5\u05d5\u05ea \u05d1\u05db\u05d5\u05d5\u05e0\u05d4",
    ]
    current_actor = (
        r"(?:\u05d4\u05de\u05e2\u05e8\u05e2\u05e8(?:\u05d9\u05dd|\u05ea)?|"
        r"\u05d4\u05e0\u05d0\u05e9\u05dd(?:\u05d9\u05dd|\u05ea)?|"
        r"\u05d4\u05de\u05d1\u05e7\u05e9(?:\u05d9\u05dd|\u05ea)?|"
        r"\u05d4\u05e2\u05d5\u05e8\u05e8(?:\u05d9\u05dd|\u05ea)?|"
        r"\u05d4\u05de\u05e9\u05d9\u05d1(?:\u05d9\u05dd|\u05d4)?)"
    )
    murder_offense = (
        r"(?:\u05e2\u05d1\u05d9\u05e8(?:\u05ea|\u05d4|\u05d5\u05ea) (?:\u05e9\u05dc )?\u05e8\u05e6\u05d7|"
        r"\u05d1\u05e8\u05e6\u05d7|"
        r"\u05d4?\u05e8\u05e6\u05d7|"
        r"\u05d1?\u05e8\u05e6\u05d9\u05d7(?:\u05ea\u05d5|\u05ea\u05d4|\u05d4|\u05d5\u05ea)?|"
        r"\u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05e8\u05e6\u05d7|"
        r"\u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05dc\u05e8\u05e6\u05d7|"
        r"\u05e8\u05e6\u05d7 \u05dc\u05e4\u05d9 \u05e1\u05e2\u05d9\u05e3\s*300|"
        r"\u05e1\u05e2\u05d9\u05e3\s*300|"
        r"\u05e7\u05e9\u05d9\u05e8\u05ea \u05e7\u05e9\u05e8 \u05dc\u05e8\u05e6\u05d7)"
    )
    homicide_other_offense = (
        r"(?:\u05d4\u05e8\u05d9\u05d2\u05d4|"
        r"\u05d4\u05e8\u05d9\u05d2\u05ea|"
        r"\u05d4\u05de\u05ea\u05d4(?: \u05d1\u05e7\u05dc\u05d5\u05ea \u05d3\u05e2\u05ea)?|"
        r"\u05d2\u05e8\u05d9\u05de\u05ea \u05de\u05d5\u05d5\u05ea|"
        r"\u05d2\u05e8\u05d9\u05de\u05ea \u05de\u05d5\u05ea\u05d5|"
        r"\u05de\u05d5\u05d5\u05ea \u05d1\u05db\u05d5\u05d5\u05e0\u05d4)"
    )
    current_case_murder_patterns = [
        r"(?:\u05d4\u05de\u05e2\u05e8\u05e2\u05e8|\u05d4\u05e0\u05d0\u05e9\u05dd|\u05d4\u05de\u05d1\u05e7\u05e9)[^.]{0,100}\u05d4\u05d5\u05e8\u05e9\u05e2[^.]{0,100}\u05e8\u05e6\u05d7",
        r"\u05d4\u05d5\u05e8\u05e9\u05e2[^.]{0,60}\u05d1\u05e2\u05d1\u05d9\u05e8\u05ea \u05e8\u05e6\u05d7",
        r"\u05e8\u05e6\u05d7[^.]{0,80}\u05e1\u05e2\u05d9\u05e3\s*300",
        r"\u05e1\u05e2\u05d9\u05e3\s*300[^.]{0,80}\u05e8\u05e6\u05d7",
        rf"{current_actor}[^.]{{0,160}}(?:\u05d4\u05d5\u05e8\u05e9\u05e2|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d5|\u05d4\u05d5\u05d0\u05e9\u05dd|\u05d4\u05d5\u05d0\u05e9\u05de\u05d4|\u05d4\u05d5\u05d0\u05e9\u05de\u05d5|\u05d9\u05d5\u05d7\u05e1(?:\u05d4|\u05d5)? \u05dc(?:\u05d5|\u05d4|\u05d4\u05dd)|\u05d9\u05d5\u05d7\u05e1\u05d5 \u05dc(?:\u05d5|\u05d4|\u05d4\u05dd))[^.]{{0,180}}{murder_offense}",
        rf"(?:\u05d4\u05d5\u05e8\u05e9\u05e2|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d5)[^.]{{0,80}}{current_actor}[^.]{{0,180}}{murder_offense}",
        rf"(?:\u05d4\u05e8\u05e9\u05d9\u05e2|\u05d4\u05e8\u05e9\u05d9\u05e2\u05d4|\u05d4\u05e8\u05e9\u05d9\u05e2\u05d5)[^.]{{0,80}}{current_actor}[^.]{{0,180}}{murder_offense}",
        rf"(?:\u05e0\u05d2\u05d3|\u05db\u05e0\u05d2\u05d3) {current_actor}[^.]{{0,140}}(?:\u05d4\u05d5\u05d2\u05e9|\u05db\u05ea\u05d1 \u05d0\u05d9\u05e9\u05d5\u05dd)[^.]{{0,180}}{murder_offense}",
    ]
    context, phrase, position = find_first_non_citation_context(
        cleaned,
        current_case_murder_patterns,
        lambda value: is_reduced_from_murder_to_homicide_context(value) or is_prior_criminal_history_context(value),
    )
    if context:
        return {
            "offense_group": "homicide_murder",
            "murder_or_homicide": 1,
            "specific_offense_terms": phrase,
            "offense_confidence": 0.9,
            "offense_needs_review": 0,
            "offense_evidence_excerpt": context,
            "offense_evidence_location": str(position),
        }

    current_case_homicide_other_patterns = [
        rf"{current_actor}[^.]{{0,160}}(?:\u05d4\u05d5\u05e8\u05e9\u05e2|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d5|\u05d4\u05d5\u05d0\u05e9\u05dd|\u05d4\u05d5\u05d0\u05e9\u05de\u05d4|\u05d4\u05d5\u05d0\u05e9\u05de\u05d5|\u05d9\u05d5\u05d7\u05e1(?:\u05d4|\u05d5)? \u05dc(?:\u05d5|\u05d4|\u05d4\u05dd)|\u05d9\u05d5\u05d7\u05e1\u05d5 \u05dc(?:\u05d5|\u05d4|\u05d4\u05dd))[^.]{{0,180}}{homicide_other_offense}",
        rf"(?:\u05d4\u05d5\u05e8\u05e9\u05e2|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d5)[^.]{{0,80}}{current_actor}[^.]{{0,180}}{homicide_other_offense}",
        rf"(?:\u05d4\u05e8\u05e9\u05d9\u05e2|\u05d4\u05e8\u05e9\u05d9\u05e2\u05d4|\u05d4\u05e8\u05e9\u05d9\u05e2\u05d5)[^.]{{0,80}}{current_actor}[^.]{{0,180}}{homicide_other_offense}",
        rf"(?:\u05e0\u05d2\u05d3|\u05db\u05e0\u05d2\u05d3) {current_actor}[^.]{{0,140}}(?:\u05d4\u05d5\u05d2\u05e9|\u05db\u05ea\u05d1 \u05d0\u05d9\u05e9\u05d5\u05dd)[^.]{{0,180}}{homicide_other_offense}",
        rf"(?:\u05d4\u05d5\u05d7\u05dc\u05e4\u05d4|\u05d4\u05d5\u05de\u05e8\u05d4)[^.]{{0,80}}\u05e8\u05e6\u05d7[^.]{{0,120}}{homicide_other_offense}",
        rf"{homicide_other_offense}[^.]{{0,100}}(?:\u05d4\u05d5\u05d3\u05d4|\u05d4\u05d5\u05d3\u05ea\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d4|\u05d4\u05d5\u05e8\u05e9\u05e2\u05d5)",
    ]
    context, phrase, position = find_first_non_citation_context(cleaned, current_case_homicide_other_patterns)
    if context:
        return {
            "offense_group": "homicide_other",
            "murder_or_homicide": 1,
            "specific_offense_terms": phrase,
            "offense_confidence": 0.85,
            "offense_needs_review": 0,
            "offense_evidence_excerpt": context,
            "offense_evidence_location": str(position),
        }

    murder_hits = [
        term
        for term in murder_terms
        if re.search(rf"(?<![\u0590-\u05ff]){re.escape(term.casefold())}(?![\u0590-\u05ff])", lowered)
    ]
    homicide_hits = [
        term
        for term in homicide_other_terms
        if re.search(rf"(?<![\u0590-\u05ff]){re.escape(term.casefold())}(?![\u0590-\u05ff])", lowered)
    ]
    if murder_hits:
        context, first, hit_pos = find_first_term_context(cleaned, lowered, murder_hits)
        if not context:
            murder_hits = []
    weak_homicide_context = context if murder_hits else ""
    weak_homicide_terms = list(murder_hits)
    weak_homicide_pos = hit_pos if murder_hits else -1
    if homicide_hits:
        context, first, hit_pos = find_first_term_context(cleaned, lowered, homicide_hits)
        if not context:
            homicide_hits = []
    if homicide_hits:
        weak_homicide_terms.extend(homicide_hits)
        if not weak_homicide_context:
            weak_homicide_context = context
            weak_homicide_pos = hit_pos

    categories = [
        ("sexual_offense", ["\u05d0\u05d9\u05e0\u05d5\u05e1", "\u05de\u05e2\u05e9\u05d4 \u05de\u05d2\u05d5\u05e0\u05d4", "\u05e2\u05d1\u05d9\u05e8\u05d5\u05ea \u05de\u05d9\u05df"]),
        ("violent_nonsexual", ["\u05ea\u05e7\u05d9\u05e4\u05d4", "\u05d0\u05dc\u05d9\u05de\u05d5\u05ea", "\u05e9\u05d5\u05d3"]),
        ("property_fraud_theft", ["\u05d2\u05e0\u05d9\u05d1\u05d4", "\u05de\u05e8\u05de\u05d4", "\u05e9\u05d5\u05d7\u05d3", "\u05d4\u05d5\u05e0\u05d0\u05d4"]),
        ("drugs", ["\u05e1\u05dd", "\u05e1\u05de\u05d9\u05dd"]),
        ("security_terror", ["\u05d8\u05e8\u05d5\u05e8", "\u05d1\u05d9\u05d8\u05d7\u05d5\u05df", "\u05e0\u05e9\u05e7"]),
        ("traffic", ["\u05ea\u05e2\u05d1\u05d5\u05e8\u05d4", "\u05e0\u05d4\u05d9\u05d2\u05d4"]),
        ("public_corruption", ["\u05e9\u05d7\u05d9\u05ea\u05d5\u05ea", "\u05e2\u05d5\u05d1\u05d3 \u05e6\u05d9\u05d1\u05d5\u05e8", "\u05de\u05e8\u05de\u05d4 \u05d5\u05d4\u05e4\u05e8\u05ea \u05d0\u05de\u05d5\u05e0\u05d9\u05dd"]),
    ]
    for group, terms in categories:
        hits = [term for term in terms if term in cleaned]
        if hits:
            pos = cleaned.find(hits[0])
            return {
                "offense_group": group,
                "murder_or_homicide": 0,
                "specific_offense_terms": "; ".join(hits),
                "offense_confidence": 0.65,
                "offense_needs_review": 1,
                "offense_evidence_excerpt": excerpt(cleaned, pos, pos + len(hits[0])),
                "offense_evidence_location": str(pos),
            }
    if weak_homicide_terms:
        return {
            "offense_group": "unknown",
            "murder_or_homicide": 0,
            "specific_offense_terms": "; ".join(dedupe_keep_order(weak_homicide_terms)),
            "offense_confidence": 0.35,
            "offense_needs_review": 1,
            "offense_evidence_excerpt": weak_homicide_context,
            "offense_evidence_location": str(weak_homicide_pos) if weak_homicide_pos >= 0 else "",
        }
    return {
        "offense_group": "unknown",
        "murder_or_homicide": 0,
        "specific_offense_terms": "",
        "offense_confidence": 0.0,
        "offense_needs_review": 1,
        "offense_evidence_excerpt": "",
        "offense_evidence_location": "",
    }

def final_disposition_segment(text: str) -> str:
    cleaned = compact_spaces(text)
    markers = [
        "\u05e1\u05d5\u05e3 \u05d3\u05d1\u05e8",
        "\u05d0\u05e9\u05e8 \u05e2\u05dc \u05db\u05df",
        "\u05dc\u05e4\u05d9\u05db\u05da",
        "\u05d4\u05ea\u05d5\u05e6\u05d0\u05d4 \u05d4\u05d9\u05d0",
        "\u05d4\u05d5\u05d7\u05dc\u05d8",
        "\u05e0\u05d9\u05ea\u05df \u05d4\u05d9\u05d5\u05dd",
    ]
    positions = [cleaned.rfind(marker) for marker in markers if cleaned.rfind(marker) >= 0]
    if positions:
        # The operative disposition can appear before separate concurring reasons.
        return cleaned[max(0, min(positions) - 5500) :]
    return cleaned[-5000:]

def classify_appellant_type(case_name: str, text: str) -> str:
    name = compact_spaces(case_name)
    if name:
        parts = re.split(r"\s+\u05e0[.'\u05f3]?\s+", name, maxsplit=1)
        if len(parts) == 2:
            left, right = parts[0], parts[1]
            if HE_STATE in left and HE_STATE not in right:
                return "state"
            if HE_STATE in right and HE_STATE not in left:
                if is_institutional_party_name(left):
                    return "unknown"
                return "defendant"
            if is_institutional_party_name(left):
                return "unknown"
    cleaned = compact_spaces(text)
    state_appeal = "\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05de\u05d3\u05d9\u05e0\u05d4" in cleaned or "\u05d4\u05de\u05d3\u05d9\u05e0\u05d4 \u05de\u05e2\u05e8\u05e2\u05e8\u05ea" in cleaned
    defendant_appeal = any(
        marker in cleaned
        for marker in [
            "\u05d4\u05de\u05e2\u05e8\u05e2\u05e8",
            "\u05d4\u05de\u05e2\u05e8\u05e2\u05e8\u05ea",
            "\u05d4\u05e0\u05d0\u05e9\u05dd",
            "\u05d4\u05e0\u05d0\u05e9\u05de\u05ea",
            "\u05d1\u05d0 \u05db\u05d5\u05d7 \u05d4\u05de\u05e2\u05e8\u05e2\u05e8",
        ]
    )
    if state_appeal and defendant_appeal:
        return "both"
    if state_appeal:
        return "state"
    if defendant_appeal:
        return "defendant"
    return "unknown"

def classify_outcome(text: str, appellant_type: str) -> dict[str, Any]:
    final_text = final_disposition_segment(text)
    adverse_sentence_patterns = [
        r"\u05e0\u05d3\u05d7\u05d4 \u05d0\u05ea \u05e2\u05e8\u05e2\u05d5\u05e8(?:\u05d5|\u05d4)?[^.]{0,180}\u05e0\u05e7\u05d1\u05dc \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d1[^\s.]{0,12}[^.]{0,220}\u05e0\u05e2\u05de\u05d9\u05d3 \u05d0\u05ea \u05ea\u05e7\u05d5\u05e4\u05ea \u05d4\u05de\u05d0\u05e1\u05e8",
        r"\u05dc?\u05e7\u05d1\u05dc \u05d0\u05ea \u05e2\u05e8\u05e2\u05d5\u05e8(?:\u05d4)? \u05e9\u05dc \u05d4\u05de\u05d3\u05d9\u05e0\u05d4[^.]{0,180}(?:\u05e7\u05d5\u05dc\u05ea \u05d4\u05e2\u05d5\u05e0\u05e9|\u05d4\u05e2\u05d5\u05e0\u05e9)[^.]{0,220}\u05d4\u05e2\u05d5\u05e0\u05e9 \u05d9\u05e2\u05de\u05d5\u05d3 \u05e2\u05dc",
        r"\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05de\u05d3\u05d9\u05e0\u05d4[^.]{0,160}\u05de\u05ea\u05e7\u05d1\u05dc[^.]{0,220}\u05dc\u05d4\u05d7\u05de\u05d9\u05e8 \u05d1\u05e2\u05d5\u05e0\u05e9",
        r"\u05de\u05e7\u05d1\u05dc\u05d9\u05dd \u05d0\u05ea \u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05de\u05d3\u05d9\u05e0\u05d4[^.]{0,220}\u05e2\u05d5\u05e0\u05e9[^.]{0,80}\u05d9\u05d5\u05d7\u05de\u05e8",
        r"\u05de\u05e7\u05d1\u05dc\u05d9\u05dd \u05d0\u05ea \u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05de\u05d3\u05d9\u05e0\u05d4[^.]{0,220}\u05dc\u05d4\u05d7\u05de\u05d9\u05e8 \u05d1\u05e2\u05d5\u05e0\u05e9",
        r"\u05de\u05d7\u05de\u05d9\u05e8(?:\u05d9\u05dd|\u05d5\u05ea)? \u05d1\u05e2\u05d5\u05e0\u05e9(?:\u05d5|\u05d4)?",
        r"\u05dc\u05d4\u05d7\u05de\u05d9\u05e8 \u05d1\u05e2\u05d5\u05e0\u05e9(?:\u05d5|\u05d4)?",
        r"\u05d4\u05d5\u05d7\u05de\u05e8 \u05e2\u05d5\u05e0\u05e9(?:\u05d5|\u05d4)?",
        r"\u05e2\u05d5\u05e0\u05e9 \u05d4\u05de\u05d0\u05e1\u05e8 \u05d9\u05d5\u05d7\u05de\u05e8",
        r"\u05e2\u05d5\u05e0\u05e9(?:\u05d5|\u05d4)?[^.]{0,80}\u05d9\u05d5\u05d7\u05de\u05e8",
    ]
    mixed_patterns = [
        r"\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd[^.]{0,80}\u05de\u05ea\u05e7\u05d1\u05dc\u05d9\u05dd \u05d1\u05d7\u05dc\u05e7\u05dd",
        r"\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05de\u05d3\u05d9\u05e0\u05d4[^.]{0,120}\u05de\u05ea\u05e7\u05d1\u05dc[^.]{0,120}\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05e0\u05d0\u05e9\u05dd[^.]{0,120}\u05e0\u05d3\u05d7\u05d4",
        r"\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d4\u05e0\u05d0\u05e9\u05dd[^.]{0,120}\u05de\u05ea\u05e7\u05d1\u05dc \u05d1\u05d7\u05dc\u05e7\u05d5",
    ]
    sentence_patterns = [
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05e2\u05dc \u05d4\u05db\u05e8\u05e2\u05ea \u05d4\u05d3\u05d9\u05df \u05e0\u05d3\u05d7\u05d4[^.]{0,160}\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05e2\u05dc \u05d2\u05d6\u05e8 \u05d4\u05d3\u05d9\u05df \u05de\u05ea\u05e7\u05d1\u05dc",
        r"\u05e2\u05d5\u05e0\u05e9 \u05d4\u05de\u05d0\u05e1\u05e8 \u05d9\u05d5\u05e4\u05d7\u05ea",
        r"\u05d4\u05e2\u05d5\u05e0\u05e9 \u05d9\u05d5\u05e2\u05de\u05d3 \u05e2\u05dc",
        r"\u05e2\u05d5\u05e0\u05e9 \u05d4\u05de\u05d0\u05e1\u05e8[^.]{0,120}\u05d9\u05e2\u05de\u05d5\u05d3 \u05e2\u05dc",
        r"\u05d9\u05d5\u05e2\u05de\u05d3 \u05e2\u05d5\u05e0\u05e9(?:\u05d5|\u05d4)?[^.]{0,80}\u05e2\u05dc",
        r"\u05d9\u05e9 \u05de\u05e7\u05d5\u05dd \u05dc\u05d4\u05e7\u05dc[^.]{0,180}\u05d4\u05e2\u05d5\u05e0\u05e9",
        r"\u05dc\u05d4\u05e7\u05dc \u05d1\u05de\u05e7\u05e6\u05ea \u05de\u05df \u05d4\u05e2\u05d5\u05e0\u05e9",
        r"\u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05d9\u05e9\u05d0 \u05d1\u05e2\u05d5\u05e0\u05e9\u05d5 \u05d1\u05e2\u05d1\u05d5\u05d3\u05d5\u05ea \u05e9\u05d9\u05e8\u05d5\u05ea",
        r"\u05d4\u05d7\u05dc\u05d8\u05e0\u05d5 \u05dc\u05d4\u05e2\u05de\u05d9\u05d3 \u05d0\u05ea \u05ea\u05e7\u05d5\u05e4\u05ea \u05d4\u05de\u05d0\u05e1\u05e8",
        r"\u05dc\u05d4\u05e2\u05de\u05d9\u05d3 \u05d0\u05ea \u05ea\u05e7\u05d5\u05e4\u05ea \u05d4\u05de\u05d0\u05e1\u05e8",
    ]
    acquittal_patterns = [
        r"\u05d4\u05e8\u05e9\u05e2(?:\u05ea\u05d5|\u05ea\u05d4|\u05d4) \u05de\u05d1\u05d5\u05d8\u05dc\u05ea",
        r"\u05de\u05d1\u05d8\u05dc(?:\u05d9\u05dd)? \u05d0\u05ea \u05d4\u05e8\u05e9\u05e2(?:\u05ea\u05d5|\u05ea\u05d4|\u05d4)",
        r"\u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05d9\u05d6\u05d5\u05db\u05d4",
        r"\u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05de\u05d6\u05d5\u05db\u05d4",
        r"\u05d4\u05de\u05e2\u05e8\u05e2\u05e8[^.]{0,80}\u05d6\u05d5\u05db\u05d4 \u05de\u05d7\u05de\u05ea \u05d4\u05e1\u05e4\u05e7",
        r"\u05dc\u05e7\u05d1\u05dc \u05d0\u05ea \u05e2\u05e8\u05e2\u05d5\u05e8(?:\u05d5|\u05d4)?[^.]{0,160}\u05d5\u05dc\u05d6\u05db\u05d5\u05ea(?:\u05d5|\u05d4)? \u05de\u05d7\u05de\u05ea \u05d4\u05e1\u05e4\u05e7",
        r"\u05d5\u05dc\u05d6\u05db\u05d5\u05ea(?:\u05d5|\u05d4)? \u05de\u05d7\u05de\u05ea \u05d4\u05e1\u05e4\u05e7",
        r"\u05de\u05d6\u05db(?:\u05d9\u05dd|\u05d4) \u05d0\u05ea \u05d4\u05de\u05e2\u05e8\u05e2\u05e8",
    ]
    lesser_offense_patterns = [
        r"\u05e0\u05e8\u05e9\u05d9\u05e2 \u05d1\u05e2\u05d1\u05d9\u05e8\u05d4 \u05d7\u05dc\u05d5\u05e4\u05d9\u05ea",
        r"\u05d7\u05dc\u05e3 \u05d4\u05e8\u05e9\u05e2(?:\u05ea\u05d5|\u05ea\u05d4|\u05d4)[^.]{0,180}\u05e0\u05e8\u05e9\u05d9\u05e2 \u05d0\u05d5\u05ea(?:\u05d5|\u05d4) \u05d1",
        r"\u05d4\u05d5\u05e8\u05e9\u05e2 \u05d1\u05e2\u05d1\u05d9\u05e8\u05d4 \u05e4\u05d7\u05d5\u05ea\u05d4",
        r"\u05d9\u05d5\u05e8\u05e9\u05e2 \u05d1\u05e2\u05d1\u05d9\u05e8\u05d4 \u05e4\u05d7\u05d5\u05ea\u05d4",
        r"\u05d4\u05d5\u05de\u05e8\u05d4 \u05d4\u05d4\u05e8\u05e9\u05e2\u05d4 \u05dc\u05e2\u05d1\u05d9\u05e8\u05d4",
        r"\u05d4\u05e8\u05e9\u05e2\u05d4 \u05dc\u05e2\u05d1\u05d9\u05e8\u05d4 \u05e7\u05dc\u05d4 \u05d9\u05d5\u05ea\u05e8",
    ]
    remand_patterns = [
        r"\u05d4\u05ea\u05d9\u05e7 \u05d9\u05d5\u05d7\u05d6\u05e8 \u05dc\u05d1\u05d9\u05ea \u05d4\u05de\u05e9\u05e4\u05d8 \u05d4\u05de\u05d7\u05d5\u05d6\u05d9",
        r"\u05d9\u05d5\u05d7\u05d6\u05e8 \u05dc\u05d3\u05d9\u05d5\u05df \u05d7\u05d3\u05e9",
        r"\u05d9\u05d5\u05e2\u05d1\u05e8 \u05dc\u05de\u05d5\u05ea\u05d1 \u05d0\u05d7\u05e8",
        r"\u05d4\u05d3\u05d9\u05d5\u05df[^.]{0,120}\u05d9\u05d5\u05e2\u05d1\u05e8[^.]{0,80}\u05dc\u05de\u05d5\u05ea\u05d1 \u05d0\u05d7\u05e8",
    ]
    denied_patterns = [
        r"\u05d4\u05d9\u05e0\u05e0\u05d5 \u05de\u05d7\u05dc\u05d9\u05d8\u05d9\u05dd \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d3\u05d9\u05df \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05dc\u05d4\u05d9\u05d3\u05d7\u05d5\u05ea",
        r"\u05d3\u05d9\u05df \u05d4\u05e8\u05e9\u05e2(?:\u05ea|\u05ea\u05d5|\u05d4) \u05d4\u05de\u05e2\u05e8\u05e2\u05e8 \u05dc\u05e2\u05de\u05d5\u05d3 \u05d1\u05e2\u05d9\u05e0\u05d4",
        r"\u05d3\u05d5\u05d7\u05d9\u05dd \u05d0\u05e4\u05d5\u05d0 \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e6\u05d9\u05e2 \u05d0\u05e4\u05d5\u05d0 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9? \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e6\u05d9\u05e2,? \u05d0\u05e4\u05d5\u05d0,? \u05dc\u05d7\u05d1\u05e8(?:\u05d9|\u05d9\u05d9|\u05d5\u05ea\u05d9\u05d9) \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05d9\u05d9\u05ea\u05d9 \u05de\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9? \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05d9\u05d9\u05ea\u05d9 \u05de\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9? \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05e9\u05e0\u05d9 \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd",
        r"\u05d4\u05d9\u05d9\u05ea\u05d9? \u05d3\u05d5\u05d7\u05d4,? \u05d0\u05e4\u05d5\u05d0,? \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05d9\u05d9\u05ea\u05d9? \u05d3\u05d5\u05d7\u05d4(?: \u05d2\u05dd)? \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8(?: [^.]{0,80})?",
        r"\u05d4\u05d9\u05d9\u05ea\u05d9? \u05d3\u05d5\u05d7\u05d4 \u05d0\u05ea (?:\u05e9\u05e0\u05d9|\u05e9\u05dc\u05d5\u05e9\u05ea) \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd",
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8[^.]{0,40}\u05e0\u05d3\u05d7\u05d4 \u05e2\u05dc \u05e9\u05e0\u05d9 \u05d7\u05dc\u05e7\u05d9\u05d5",
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8,? \u05d0\u05dd \u05db\u05df,? \u05e0\u05d3\u05d7\u05d4",
        r"\u05d0\u05d9\u05e0\u05e0\u05d5 \u05e0\u05e2\u05ea\u05e8\u05d9\u05dd \u05d0\u05d9?[\u05e4\u05e4]\u05d5\u05d0 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05d7\u05dc\u05d8\u05ea\u05e0\u05d5 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05e0\u05d3\u05d7\u05d4 \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05e2\u05dc \u05d4\u05db\u05e8\u05e2\u05ea \u05d4\u05d3\u05d9\u05df \u05d5\u05e2\u05dc \u05d2\u05d6\u05e8 \u05d4\u05d3\u05d9\u05df",
        r"\u05e9\u05d3\u05d9\u05df \u05e9\u05e0\u05d9 \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd \u05dc\u05d4\u05d9\u05d3\u05d7\u05d5\u05ea",
        r"\u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05e9\u05e0\u05d9 \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd",
        r"\u05dc\u05d4\u05d5\u05ea\u05d9\u05e8 \u05d0\u05ea \u05d4\u05e2\u05d5\u05e0\u05e9 \u05d1\u05e2\u05d9\u05e0\u05d5[^.]{0,80}\u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05e0\u05d3\u05d7\u05d4",
        r"\u05e0\u05d3\u05d7\u05d4 \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd \u05e0\u05d3\u05d7\u05d9\u05dd",
        r"\u05d3\u05d5\u05d7\u05d9\u05dd \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e0\u05d5 \u05d3\u05d5\u05d7\u05d9\u05dd \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e0\u05d5 \u05de\u05d7\u05dc\u05d9\u05d8\u05d9\u05dd \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea [^.]{0,80}\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd",
        r"\u05d0\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d5\u05ea\u05d9\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9 \u05e9\u05dc\u05d0 \u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05e0\u05d9 \u05de\u05e6\u05d9\u05e2 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05de\u05dc\u05d9\u05e5 \u05dc\u05d7\u05d1\u05e8\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05de\u05dc\u05d9\u05e5 \u05dc\u05d7\u05d1\u05e8\u05d9\u05d9 \u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8\u05d9\u05dd",
        r"\u05dc\u05d3\u05d7\u05d5\u05ea \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05e2\u05dc \u05e9\u05e0\u05d9 \u05d7\u05dc\u05e7\u05d9\u05d5",
        r"\u05d3\u05d7\u05d9\u05d9\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05e9\u05dc\u05d0 \u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05e9\u05dc\u05d0 \u05dc\u05d4\u05ea\u05e2\u05e8\u05d1 \u05d1\u05e2\u05d5\u05e0\u05e9",
        r"\u05e9\u05dc\u05d0 \u05dc\u05d4\u05ea\u05e2\u05e8\u05d1 \u05d1\u05d4\u05e8\u05e9\u05e2\u05d4",
        r"\u05d0\u05d9\u05df \u05d1\u05d9\u05d3\u05d9\u05e0\u05d5 \u05dc\u05e7\u05d1\u05dc \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05dc\u05d0 \u05e8\u05d0\u05d9\u05e0\u05d5 \u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05d9\u05df \u05d1\u05d9\u05d3\u05d9\u05e0\u05d5 \u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05d9\u05e0\u05e0\u05d5 \u05e0\u05e2\u05ea\u05e8\u05d9\u05dd \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d0\u05d9\u05df \u05de\u05e0\u05d5\u05e1 \u05de\u05d3\u05d7\u05d9\u05d9\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05dc\u05d0 \u05e8\u05d0\u05d9\u05e0\u05d5 \u05de\u05e7\u05d5\u05dd \u05d0\u05d5 \u05e2\u05d9\u05dc\u05d4 \u05dc\u05e9\u05e0\u05d5\u05ea \u05de\u05d2\u05d6\u05e8 \u05d3\u05d9\u05e0\u05d5",
        r"\u05dc\u05d0 \u05de\u05e6\u05d0\u05e0\u05d5 \u05e2\u05d9\u05dc\u05d4 \u05dc\u05d4\u05ea\u05e2\u05e8\u05d1",
        r"\u05d4\u05d1\u05e7\u05e9\u05d4[^.]{0,100}\u05e0\u05d3\u05d7(?:\u05d9\u05ea|\u05d4)",
    ]
    accepted_patterns = [
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05de\u05ea\u05e7\u05d1\u05dc",
        r"\u05de\u05e7\u05d1\u05dc\u05d9\u05dd \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05de\u05ea\u05e7\u05d1\u05dc \u05d1\u05d7\u05dc\u05e7\u05d5",
        r"\u05d0\u05e6\u05d9\u05e2 \u05dc\u05e7\u05d1\u05dc \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05e7\u05d1\u05dc\u05ea\u05d5 \u05e9\u05dc \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05d9\u05e9 \u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
        r"\u05dc\u05d4\u05d9\u05e2\u05ea\u05e8 \u05dc\u05e2\u05e8\u05e2\u05d5\u05e8",
    ]
    checks = [
        ("defendant_adverse_sentence_increased", -1, "sentence_increased_or_state_relief", adverse_sentence_patterns, 0.88, 0),
        ("mixed_or_unclear", 5, "mixed_or_unclear", mixed_patterns, 0.55, 1),
        ("conviction_reversed_or_acquittal", 3, "conviction_reversed_or_acquittal", acquittal_patterns, 0.88, 0),
        ("conviction_modified_lesser_offense", 2, "conviction_modified_lesser_offense", lesser_offense_patterns, 0.86, 0),
        ("sentence_relief_only", 1, "sentence_relief_only", sentence_patterns, 0.82, 0),
        ("remand_or_new_hearing", 4, "remand_or_new_hearing", remand_patterns, 0.8, 0),
        ("no_defendant_relief", 0, "none", denied_patterns, 0.82, 0),
        ("accepted_uncategorized", 5, "mixed_or_unclear", accepted_patterns, 0.55, 1),
    ]
    for raw, normalized, relief, patterns, confidence, needs_review in checks:
        context, phrase, _ = find_first_context(final_text, patterns)
        if not context:
            continue
        if raw == "defendant_adverse_sentence_increased" and appellant_type == "defendant":
            explicit_companion_appeal = bool(
                (
                    re.search(r"\u05e0\u05e7\u05d1\u05dc \u05d0\u05ea \u05d4\u05e2\u05e8\u05e2\u05d5\u05e8 \u05d1", context)
                    and re.search(r"\u05e0\u05e2\u05de\u05d9\u05d3 \u05d0\u05ea \u05ea\u05e7\u05d5\u05e4\u05ea \u05d4\u05de\u05d0\u05e1\u05e8", context)
                )
                or bool(
                    re.search(r"\u05e2\u05e8\u05e2\u05d5\u05e8(?:\u05d4)? \u05e9\u05dc \u05d4\u05de\u05d3\u05d9\u05e0\u05d4", context)
                    and re.search(r"\u05d4\u05e2\u05d5\u05e0\u05e9 \u05d9\u05e2\u05de\u05d5\u05d3 \u05e2\u05dc", context)
                )
            )
            if not explicit_companion_appeal:
                continue
        favorable: int | None
        direction: int | None
        if raw == "defendant_adverse_sentence_increased":
            favorable = 0
            direction = -1
        elif appellant_type == "state":
            if normalized == 0:
                raw = "state_appeal_denied"
                favorable = 1
                direction = 0
            elif raw == "accepted_uncategorized":
                raw = "state_appeal_accepted"
                normalized = -1
                relief = "state_appeal_accepted_defendant_adverse"
                favorable = 0
                direction = -1
            else:
                favorable = 0 if normalized in {1, 2, 3, 4, 5} else 1
                direction = -1 if normalized in {1, 2, 3, 4, 5} else 0
                needs_review = 1
        elif appellant_type == "both":
            favorable = None
            direction = None
            needs_review = 1
            normalized = 5
            relief = "mixed_or_unclear"
        else:
            favorable = 0 if normalized == 0 else (1 if normalized in {1, 2, 3, 4} else None)
            direction = 0 if normalized == 0 else (1 if normalized in {1, 2, 3, 4} else None)
        return {
            "appeal_outcome_raw": raw if raw != "accepted_uncategorized" else "appeal_accepted_uncategorized",
            "appeal_outcome_normalized": normalized,
            "defendant_favorable_outcome": favorable,
            "defendant_outcome_direction": direction,
            "relief_type": relief,
            "outcome_confidence": confidence,
            "outcome_needs_review": needs_review,
            "outcome_evidence_excerpt": context or phrase,
        }
    return {
        "appeal_outcome_raw": "unknown",
        "appeal_outcome_normalized": 5,
        "defendant_favorable_outcome": None,
        "defendant_outcome_direction": None,
        "relief_type": "mixed_or_unclear",
        "outcome_confidence": 0.0,
        "outcome_needs_review": 1,
        "outcome_evidence_excerpt": "",
    }

def is_anonymous_name(value: str) -> bool:
    cleaned = compact_spaces(value).strip(" \"'.,:;|").casefold()
    return bool(
        re.fullmatch(
            r"(?:\u05e4\u05dc\u05d5\u05e0\u05d9|\u05e4\u05dc\u05d5\u05e0\u05d9\u05ea|\u05d0\u05dc\u05de\u05d5\u05e0\u05d9|\u05d0\u05dc\u05de\u05d5\u05e0\u05d9\u05ea)",
            cleaned,
        )
    )

def is_institutional_party_name(value: str) -> bool:
    cleaned = compact_spaces(value).strip(" \"'.,:;|")
    return any(marker in cleaned for marker in INSTITUTIONAL_PARTY_MARKERS)

def primo_case_party_name(case_name: str) -> str:
    party_names = [name for name in infer_case_party_names(case_name) if not is_anonymous_name(name)]
    return next((name for name in party_names if not is_institutional_party_name(name)), "")

